### PR TITLE
Remove portscan

### PR DESCRIPTION
**Pull request by thc202**
As per plan of discontinuing the portscan add-on, as better/specific tools exist.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
Changed to WIP to wait for https://groups.google.com/g/zaproxy-users/c/6yHEdPz3Zrc/m/_2C7GRmeBQAJ

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Comment by psiinon** [comment]
No replies on that thread, I'm good for this to be merged now 😁

**Comment by thc202** [comment]
Should we also remove from stable?

**Comment by psiinon** [comment]
I think so .. we can always add it back in if people complain...

**Comment by thc202** [comment]
Done.

**Pull request merged**
