### PR TITLE
retire & encoder: release version 0.1.0

### PR DESCRIPTION
**Pull request by kingthorin**

### CODE REVIEW

**Comment by thc202** [comment]
In 2.9.0 it will log warnings because of the duplicate shortcut, e.g.:
```
[ZAP-BootstrapGUI] WARN org.zaproxy.zap.extension.keyboard.ExtensionKeyboard  - Menus encoder.tools.menu.encdec and enc2.tools.menu.encdec use the same default accelerator: ctrl pressed E
```

There's also an error when installing (first time), I didn't notice this one :/
```
ERROR org.zaproxy.zap.extension.keyboard.ExtensionKeyboard  - No mapping found for keyboard shortcut: encoder.tools.menu.encdec
```

I think it's fine to release anyway, thoughts?

**Comment by kingthorin** [comment]
I never hit that error, weird.

I think it's okay to go anyway.

**Comment by thc202** [comment]
I might look at that before then ;) (I think it's because of core not picking up the menu when added...)

OK, lets wait for what @psiinon says.

**Comment by thc202** [comment]
For the record, that error is indeed caused by the extension keyboard not knowing of the new menu(s) when an add-on is installed.

**Pull request merged**
