### PR TITLE
chore: Standardize on the use of "status" vs "quality"

### PR DESCRIPTION
**Pull request by kingthorin**
Update the HelpGenerator, ZapVersions-2.11.xml, and ZapVersions-dev.xml.

Related to zaproxy/zaproxy#4732

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
It's only necessary to update `ZapVersions-2.11.xml`.

**Comment by kingthorin** [comment]
Isn't dev used for the weekly? Shouldn't the HelpGenerator prompt match as well if we're standardizing?

**Comment by thc202** [comment]
I was talking just about the `ZapVersions` files, the `dev` is not used to generate website data.

**Comment by kingthorin** [comment]
Tweaked.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
