### PR TITLE
Release Levo.ai v0.1.0

### PR DESCRIPTION
**Pull request by ricekot**

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
I had a quick look at the code. I'm not a kotlin person but it seems pretty straight forward.

The only thing that stood out to me is that the local destination (localhost:9999) seems to be statically defined. But that can be addressed in a future iteration.

**Comment by ricekot** [comment]
That is a default value for the parameter. The add-on also adds an options panel that allows specifying a different URL.
image

**Comment by kingthorin** [comment]
Even better! Sorry I missed it.

**Comment by ricekot** [comment]
No worries!

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
