### PR TITLE
Include SBOM components' version when sorting

### PR DESCRIPTION
**Pull request by thc202**
Ensure the components have a predictable order always.
Also, use a set to avoid listing duplicates.

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]
I’m assuming the version element comparator properly handles whole numbers, semver, whatever?

**Comment by thc202** [comment]
It just compares them as string, the order is not really relevant as long as it is consistent between runs.

**Comment by kingthorin** [comment]
Okay

**Comment by kingthorin** [comment]
The merge workflow is failing, the first run it seems to have been because of networking issues. Seems to be an incident: https://www.githubstatus.com/incidents/pxg3dz4yg7lp

**Comment by kingthorin** [comment]
The merge workflow keeps failing, the first time it seems to have been networking related

**Pull request merged**
