### PR TITLE
Filter locale from translation deployment

### PR DESCRIPTION
**Pull request by thc202**
Do not copy translations of newer locale that does not have any.

---
WIP pending update of the Crowdin plugin in the respective repos.

### CODE REVIEW

**Comment by psiinon** [comment]
Will we need to manage these manally?

**Comment by thc202** [comment]
For the time being we just have one, but I will look at adding the percentage checks.

**Comment by psiinon** [comment]
We could also remove langs with no transaltions that have been there for a while .. if there are any?

**Comment by thc202** [comment]
From a quick look Hausa and Macedonian seem to be at 0% for all files.

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
